AuthorBooksBcs6CWebApplication1/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AuthorBooksBcs6CWebApplication1.Models
{
    public class Book
    {
        public int bid { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public int publishyear { get; set; }
        public int aid { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public string Gender { get; set; }
        public string email { get; set; }

    }
}

AuthorBooksBcs6CWebApplication1/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using AuthorBooksBcs6CWebApplication1.Models;
namespace AuthorBooksBcs6CWebApplication1.Controllers
{
    public class BookController : Controller
    {
         string constr = "Data Source=DESKTOP-FMO6LUK;Initial Catalog=AuthorBook;Integrated Security=True";
        // GET: Book
        [HttpGet]
        public ActionResult BookEntry()
        {
            return View();
        }
        //For data insertion in book table 
        [HttpPost]
        public ActionResult BookEntry(Book a)
        {         
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            //Response.Write("<script> alert('Connect with server!');</script>");
            string q = "insert into Books (title,category,publishyear,aid) values ('" + a.title + "','" + a.category + "','" + a.publishyear + "',"+a.aid+")";
            SqlCommand cmd = new SqlCommand(q, con);
            cmd.ExecuteNonQuery();
            con.Close();
            Response.Write("<script> alert('Record saved!');</script>");
            return RedirectToAction("BooksRecords");
        }

        //For showing book data from database to view
        private List<Book> getBook()
        {
            List<Book> alist = new List<Book>();
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q = "Select bid,title,category,publishyear,aid from books";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                Book b = new Book();
                b.bid = int.Parse(sdr["bid"].ToString());
                b.title = sdr["title"].ToString();
                b.category = sdr["category"].ToString();
                b.publishyear = int.Parse(sdr["publishyear"].ToString());
                b.aid = int.Parse(sdr["aid"].ToString());
                alist.Add(b);
            }

            con.Close();
            return alist;
        }
        [HttpGet]
        public ActionResult BooksRecords()
        {
            List<Book> bk = getBook();
            return View(bk);
        }
        private List<Book> getBook(string cat)
        {
            List<Book> alist = new List<Book>();
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q = "Select bid,title,category,publishyear from books where category='" + cat + "'";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                Book b = new Book();
                b.bid = int.Parse(sdr["bid"].ToString());
                b.title = sdr["title"].ToString();
                b.category = sdr["category"].ToString();
                b.publishyear = int.Parse(sdr["publishyear"].ToString());
                
                alist.Add(b);
            }

            con.Close();
            return alist;
        }
        [HttpPost]
        public ActionResult BooksRecords(string cattb)
        {
            List<Book> bk = getBook(cattb);
            return View(bk);
        }
        

    }
}

AuthorBooksBcs6CWebApplication1/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using PagedList;
using PagedList.Mvc;
using AuthorBooksBcs6CWebApplication1.Models;
                     //***************After Mid Work****************************************
namespace AuthorBooksBcs6CWebApplication1.Controllers
{               
    public class BooksController : Controller
    {
        // GET: Books
        string constr = "Data Source=DESKTOP-FMO6LUK;Initial Catalog=AuthorBook;Integrated Security=True";
        //private List<SelectListItem> getCat()
        //{
        //    List<SelectListItem> bookCat = new List<SelectListItem>();
        //    SqlConnection con = new SqlConnection(constr);
        //    con.Open();
        //    string q;
            
        //     q = "select distinct category  from Books";
            
        //    SqlCommand cmd = new SqlCommand(q, con);
        //    SqlDataReader sdr = cmd.ExecuteReader();
        //    while (sdr.Read())
        //    {
        //        bookCat.Add(new SelectListItem { Text = sdr[0].ToString(), Value = sdr[0].ToString() });
        //    }
        //    sdr.Close();
        //    con.Close();
          
            
        //    return bookCat;
        //}
        //private List<Book> getBook(string cat)
        //{
        //    List<Book> alist = new List<Book>();
        //    SqlConnection con = new SqlConnection(constr);
        //    con.Open();
        //    string q;
        //    if (!String.IsNullOrEmpty(cat))
        //    {
        //        q = "select b.bid,b.title,b.category,b.publishyear,b.aid,a.name from author a inner join books b on a.aid=b.aid where b.category = '" + cat + "'";
        //    }
        //    else
        //    {
        //        q = "select b.bid,b.title,b.category,b.publishyear,b.aid,a.name from author a inner join books b on a.aid=b.aid";
        //    }
        //    SqlCommand cmd = new SqlCommand(q, con);
        //    SqlDataReader sdr = cmd.ExecuteReader();
        //    while (sdr.Read())
        //    {
        //        Book b = new Book();
        //        b.bid = int.Parse(sdr["bid"].ToString());
        //        b.title = sdr["title"].ToString();
        //        b.category = sdr["category"].ToString();
        //        b.publishyear = int.Parse(sdr["publishyear"].ToString());
        //        b.aid = int.Parse(sdr["aid"].ToString());
        //        b.name = sdr["name"].ToString();

        //        alist.Add(b);
        //    }

        //    con.Close();
        //    return alist;
        //}



        //[HttpGet]
        //public ActionResult BooksSearch(String cattb, int? page)
        //{
        //    ViewBag.Cat = getCat();
        //    List<Book> bs = getBook(cattb);
        //    return View(bs.ToPagedList(page ?? 1, 3));    //one represent from where it start and 3 how many record on one page show

        //}


        private List<Book> getBook1(string cont, string SearchBy)
        {
            List<Book> alist = new List<Book>();
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q;
            if (!String.IsNullOrEmpty(cont))
            {
                //q = "select * from books b inner join author a on a.aid=b.bid where "+ SearchBy + " like '"+ cont + "%'";
                q = "select name,gender,email from author where "+ SearchBy + " like '" + cont + "%'";
            }
            else
            {
                //q = "select * from books b inner join author a on a.aid=b.bid ";
                q = "select name,gender,email from author";
            }


            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                Book b = new Book();
                //b.bid = int.Parse(sdr["bid"].ToString());
                //b.title = sdr["title"].ToString();
               // b.category = sdr["category"].ToString();
                //b.publishyear = int.Parse(sdr["publishyear"].ToString());
                //b.aid = int.Parse(sdr["aid"].ToString());
                b.name = sdr["name"].ToString();
                //b.country = sdr["country"].ToString();
                b.Gender = sdr["gender"].ToString();
                b.email = sdr["email"].ToString();
                alist.Add(b);
            }
            con.Close();
            return alist;
        }


        [HttpGet]
        public ActionResult BooksSearch(string cont, string SearchBy, int? page)
        {
            List<Book> bs = getBook1(cont, SearchBy);

            return View(bs.ToPagedList(page ?? 1, 3));    //one represent from where it start and 3 how many record on one page show

        }
    }
}

AuthorBooksBcs6CWebApplication1/Views/Book/BookEntry.cshtml
@model AuthorBooksBcs6CWebApplication1.Models.Book

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BookEntry</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.publishyear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.publishyear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.publishyear, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.aid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.aid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.aid, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "BooksRecords")
    </div>
</body>
</html>

AuthorBooksBcs6CWebApplication1/Views/Book/BooksRecords.cshtml
@model IEnumerable<AuthorBooksBcs6CWebApplication1.Models.Book>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BooksRecords</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "BookEntry")
    </p>
    @using (Html.BeginForm("BooksRecords", "Book",FormMethod.Post))
    {
        <b>Enter Category:</b>
        @Html.TextBox("cattb")
        <input type="submit" value="Submit">
    }
        <table border="1" class="table">
            <tr>
                <th>
                   Book ID
                </th>
                <th>
                    Title
                </th>
                <th>
                    Category
                </th>
                <th>
                    Publish Year
                </th>
                <th>
                    Author Id
                </th>
                <th>Action Links</th>
            </tr>

            @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.bid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.publishyear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.aid)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
            }

        </table>
    </body>
</html>