AuthorBooksBcs6CWebApplication1/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AuthorBooksBcs6CWebApplication1.Models
{
    public class Book
    {
        public int bid { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public int publishyear { get; set; }
        public int aid { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public string Gender { get; set; }
        public string email { get; set; }

    }
}

AuthorBooksBcs6CWebApplication1/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using AuthorBooksBcs6CWebApplication1.Models;
namespace AuthorBooksBcs6CWebApplication1.Controllers
{
    public class BookController : Controller
    {
         string constr = "Data Source=DESKTOP-FMO6LUK;Initial Catalog=AuthorBook;Integrated Security=True";
        // GET: Book
        [HttpGet]
        public ActionResult BookEntry()
        {
            return View();
        }
        //For data insertion in book table 
        [HttpPost]
        public ActionResult BookEntry(Book a)
        {         
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            //Response.Write("<script> alert('Connect with server!');</script>");
            string q = "insert into Books (title,category,publishyear,aid) values ('" + a.title + "','" + a.category + "','" + a.publishyear + "',"+a.aid+")";
            SqlCommand cmd = new SqlCommand(q, con);
            cmd.ExecuteNonQuery();
            con.Close();
            Response.Write("<script> alert('Record saved!');</script>");
            return RedirectToAction("BooksRecords");
        }

        //For showing book data from database to view
        private List<Book> getBook()
        {
            List<Book> alist = new List<Book>();
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q = "Select bid,title,category,publishyear,aid from books";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                Book b = new Book();
                b.bid = int.Parse(sdr["bid"].ToString());
                b.title = sdr["title"].ToString();
                b.category = sdr["category"].ToString();
                b.publishyear = int.Parse(sdr["publishyear"].ToString());
                b.aid = int.Parse(sdr["aid"].ToString());
                alist.Add(b);
            }

            con.Close();
            return alist;
        }
        [HttpGet]
        public ActionResult BooksRecords()
        {
            List<Book> bk = getBook();
            return View(bk);
        }
        private List<Book> getBook(string cat)
        {
            List<Book> alist = new List<Book>();
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q = "Select bid,title,category,publishyear from books where category='" + cat + "'";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                Book b = new Book();
                b.bid = int.Parse(sdr["bid"].ToString());
                b.title = sdr["title"].ToString();
                b.category = sdr["category"].ToString();
                b.publishyear = int.Parse(sdr["publishyear"].ToString());
                
                alist.Add(b);
            }

            con.Close();
            return alist;
        }
        [HttpPost]
        public ActionResult BooksRecords(string cattb)
        {
            List<Book> bk = getBook(cattb);
            return View(bk);
        }
        

    }
}

AuthorBooksBcs6CWebApplication1/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using PagedList;
using PagedList.Mvc;
using AuthorBooksBcs6CWebApplication1.Models;
                     //***************After Mid Work****************************************
namespace AuthorBooksBcs6CWebApplication1.Controllers
{               
    public class BooksController : Controller
    {
        // GET: Books
        string constr = "Data Source=DESKTOP-FMO6LUK;Initial Catalog=AuthorBook;Integrated Security=True";
        //private List<SelectListItem> getCat()
        //{
        //    List<SelectListItem> bookCat = new List<SelectListItem>();
        //    SqlConnection con = new SqlConnection(constr);
        //    con.Open();
        //    string q;
            
        //     q = "select distinct category  from Books";
            
        //    SqlCommand cmd = new SqlCommand(q, con);
        //    SqlDataReader sdr = cmd.ExecuteReader();
        //    while (sdr.Read())
        //    {
        //        bookCat.Add(new SelectListItem { Text = sdr[0].ToString(), Value = sdr[0].ToString() });
        //    }
        //    sdr.Close();
        //    con.Close();
          
            
        //    return bookCat;
        //}
        //private List<Book> getBook(string cat)
        //{
        //    List<Book> alist = new List<Book>();
        //    SqlConnection con = new SqlConnection(constr);
        //    con.Open();
        //    string q;
        //    if (!String.IsNullOrEmpty(cat))
        //    {
        //        q = "select b.bid,b.title,b.category,b.publishyear,b.aid,a.name from author a inner join books b on a.aid=b.aid where b.category = '" + cat + "'";
        //    }
        //    else
        //    {
        //        q = "select b.bid,b.title,b.category,b.publishyear,b.aid,a.name from author a inner join books b on a.aid=b.aid";
        //    }
        //    SqlCommand cmd = new SqlCommand(q, con);
        //    SqlDataReader sdr = cmd.ExecuteReader();
        //    while (sdr.Read())
        //    {
        //        Book b = new Book();
        //        b.bid = int.Parse(sdr["bid"].ToString());
        //        b.title = sdr["title"].ToString();
        //        b.category = sdr["category"].ToString();
        //        b.publishyear = int.Parse(sdr["publishyear"].ToString());
        //        b.aid = int.Parse(sdr["aid"].ToString());
        //        b.name = sdr["name"].ToString();

        //        alist.Add(b);
        //    }

        //    con.Close();
        //    return alist;
        //}



        //[HttpGet]
        //public ActionResult BooksSearch(String cattb, int? page)
        //{
        //    ViewBag.Cat = getCat();
        //    List<Book> bs = getBook(cattb);
        //    return View(bs.ToPagedList(page ?? 1, 3));    //one represent from where it start and 3 how many record on one page show

        //}


        private List<Book> getBook1(string cont, string SearchBy)
        {
            List<Book> alist = new List<Book>();
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q;
            if (!String.IsNullOrEmpty(cont))
            {
                //q = "select * from books b inner join author a on a.aid=b.bid where "+ SearchBy + " like '"+ cont + "%'";
                q = "select name,gender,email from author where "+ SearchBy + " like '" + cont + "%'";
            }
            else
            {
                //q = "select * from books b inner join author a on a.aid=b.bid ";
                q = "select name,gender,email from author";
            }


            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                Book b = new Book();
                //b.bid = int.Parse(sdr["bid"].ToString());
                //b.title = sdr["title"].ToString();
               // b.category = sdr["category"].ToString();
                //b.publishyear = int.Parse(sdr["publishyear"].ToString());
                //b.aid = int.Parse(sdr["aid"].ToString());
                b.name = sdr["name"].ToString();
                //b.country = sdr["country"].ToString();
                b.Gender = sdr["gender"].ToString();
                b.email = sdr["email"].ToString();
                alist.Add(b);
            }
            con.Close();
            return alist;
        }


        [HttpGet]
        public ActionResult BooksSearch(string cont, string SearchBy, int? page)
        {
            List<Book> bs = getBook1(cont, SearchBy);

            return View(bs.ToPagedList(page ?? 1, 3));    //one represent from where it start and 3 how many record on one page show

        }
    }
}

AuthorBooksBcs6CWebApplication1/Views/Books/BooksSearch.cshtml
@using PagedList.Mvc;
@using PagedList;
 
@model IPagedList<AuthorBooksBcs6CWebApplication1.Models.Book>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BooksSearch</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    @*//This is for search through search box*@

    @using (Html.BeginForm("BooksSearch", "Books", FormMethod.Get))
    {

        <b>Search By:</b>
        @Html.RadioButton("SearchBy", "Name",true)<text>Name</text>
        @Html.RadioButton("SearchBy", "Gender")<text>Gender</text>

        <br><b>Search:</b>
        @Html.TextBox("cont")
        <input type="submit" value="Submit">
    }

    @*//This is for search through dropdown menu*@
    @*@using (Html.BeginForm("BooksSearch", "Books", FormMethod.Get))
        {
                <table>

                    <tr>
                        <td>Select Category</td>
                        <td>
                            @Html.DropDownList("cattb", (List<SelectListItem>)ViewBag.Cat, "Select")

                        </td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="Submit"></td>

                    </tr>
                </table>
        }*@





    @if (Model.Count() == 0)
    {
        <b>No Records</b>
    }
    else
    {

        <table border="1" class="table">
            <tr>
                @*<th>
                    @Html.DisplayNameFor(model => model.First().bid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().publishyear)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().aid)
                </th>

                        <th>
                    @Html.DisplayNameFor(model => model.First().country)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.First().name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Gender)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().email)
                </th>
            </tr>

            @foreach (var item in Model)
            {
             <tr>
                    @*<td>
                    @Html.DisplayFor(modelItem => item.bid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.publishyear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aid)
                </td>

                    <td>
                    @Html.DisplayFor(modelItem => item.country)
                </td>*@
                    <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>

            @*<td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>*@
        </tr>
            }

        </table>
    }
    @Html.PagedListPager(Model, page => Url.Action("BooksSearch", new { page, cont = Request.QueryString["cont"], SearchBy = Request.QueryString["SearchBy"] }), new PagedListRenderOptions() { DisplayItemSliceAndTotal = true })
    
    

</body>
</html>