AuthorBooksBcs6CWebApplication1/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AuthorBooksBcs6CWebApplication1.Models
{
    public class Author
    {
        
            public int aid { get; set; }
            public string Name { get; set; }
            public string Country { get; set; }
            public string Gender { get; set; }
            public bool Married { get; set; }
        
    }
}

AuthorBooksBcs6CWebApplication1/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuthorBooksBcs6CWebApplication1.Models;
using System.Data.SqlClient;
namespace AuthorBooksBcs6CWebApplication1.Controllers
{
    public class AuthorController : Controller
    {
        string constr = "Data Source=DESKTOP-FMO6LUK;Initial Catalog=AuthorBook;Integrated Security=True";
        // GET: Author
        public ActionResult AuthorDetails()
        {
            //Filling author Object using C# Object Initializer Syntax
            Author author = new Author()
            {
                aid = 1,
                Name = "Ali",
                Country = "Pakistan",
                Gender = "Male",
                Married = true
            };
            //Passing author Object to AuthorDetails.cshtml
            return View(author);
        }
        public ActionResult AuthorsList()
        {
            //Creating 3 author Objects using C# Object Initializer Syntax
            Author author1 = new Author()
            {
                aid = 1,
                Name = "Ali",
                Country = "Pakistan",
                Gender = "Male",
                Married = true
            };
            Author author2 = new Author
            {
                aid = 2,
                Name = "Aliza",
                Country = "Pakistan",
                Gender = "Feale",
                Married = true
            };
            Author author3 = new Author
            {
                aid = 3,
                Name = "Umer",
                Country = "BD",
                Gender = "Male",
                Married = false
            };
            List<Author> AuthorsList = new List<Author>() { author1, author2, author3 };
            return View(AuthorsList);
        }
        private List<SelectListItem> getCountries()
        {
            List<SelectListItem> bookTypeList = new List<SelectListItem>();
            bookTypeList.Add(new SelectListItem { Text = "Pakistan", Value = "Pakstan" });
            bookTypeList.Add(new SelectListItem { Text = "India", Value = "India" });
            bookTypeList.Add(new SelectListItem { Text = "Afghanistan", Value = "Afghanistan" });
            return bookTypeList;
        }
        [HttpGet]
        public ActionResult authorEntry()
        {
            ViewBag.Countries = getCountries();
            return View();
        }
        [HttpPost]
        public ActionResult authorEntry(Author a)
        {
            string msta = "";
            
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            //Response.Write("<script> alert('Connect with server!');</script>");
            if (a.Married == true)
            {
                msta = "Yes";
            }
            else
            {
                msta = "No";
            }
            string query = "insert into author(name,country,Gender,mstaus) values('" + a.Name + "','" + a.Country + "','" + a.Gender + "','" + msta + "')";
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.ExecuteNonQuery();
            con.Close();
            Response.Write("<script> alert('Record saved!');</script>");
            return RedirectToAction("AuthorsRecords");
        }

        private List<Author> getAuthors()
        {
            List<Author> alist = new List<Author>();
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q = "Select aid,name from author";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                Author a = new Author();
                a.aid = int.Parse(sdr["aid"].ToString());
                a.Name = sdr["name"].ToString();
                alist.Add(a);
            }

            con.Close();
            return alist;
        }
        [HttpGet]
        public ActionResult AuthorsRecords()
        {
            List<Author> al = getAuthors();
            return View(al);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q = "Select aid,name,country,gender,mstaus from author where aid='" + id + "'";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            sdr.Read();
            Author a = new Author();
            a.aid = int.Parse(sdr["aid"].ToString());
            a.Name = sdr["name"].ToString();
            a.Country = sdr["country"].ToString();
            if (sdr["gender"].ToString() == "M")
                a.Gender = "Male";
            else
                a.Gender = "Female";

            if (sdr["mstaus"].ToString() == "Yes")
                a.Married = true;
            else
                a.Married = false;

            sdr.Close();
            con.Close();

            return View(a);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            SqlConnection con = new SqlConnection(constr);
            con.Open();
            SqlCommand cmd = new SqlCommand("Delete from author where aid ='" + id + "'", con);
            cmd.ExecuteNonQuery();
            con.Close();
            return RedirectToAction("AuthorsRecords");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            SqlConnection con = new SqlConnection(constr);
            con.Open();
            string q = "Select aid,name,country,gender from author where aid ='" + id + "'";
            SqlCommand cmd = new SqlCommand(q, con);
            SqlDataReader sdr = cmd.ExecuteReader();
            sdr.Read();
            Author a = new Author();
            a.aid = int.Parse(sdr["aid"].ToString());
            a.Name = sdr["name"].ToString();
            a.Country = sdr["country"].ToString();
            a.Gender = sdr["gender"].ToString();
            sdr.Close();
            con.Close();

            return View(a);
        }

        [HttpPost]
        public ActionResult Edit(Author a)
        {

            SqlConnection con = new SqlConnection(constr);
            con.Open();
            SqlCommand cmd = new SqlCommand("update author set name='" + a.Name + "',country='" + a.Country + "',gender='" + a.Gender + "' where aid ='" + a.aid + "' ", con);
            cmd.ExecuteNonQuery();
            con.Close();
            return RedirectToAction("AuthorsRecords");
        }
       
    }
}

AuthorBooksBcs6CWebApplication1/Views/Author/AuthorDetails.cshtml
@model AuthorBooksBcs6CWebApplication1.Models.Author

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AuthorDetails</title>
</head>
<body>
    <h2>Author Detail</h2>
    <div>
        <b> Author Id:</b>@Model.aid <br />
        <b> Author Name:</b> @Model.Name <br />
        <b> Author Country:</b>@Model.Country <br />
        <b> Author Gender:</b>@Model.Gender <br />
        <b> Married? :</b>@Model.Married
    </div>
</body>
</html>

AuthorBooksBcs6CWebApplication1/Views/Author/AuthorsList.cshtml
@model List<AuthorBooksBcs6CWebApplication1.Models.Author>
@{ Layout = null; }

<!DOCTYPE html>

<html>

<head>
    <title> Model List  Demo </title>

</head>

<body>

    <h1> Authors List</h1>

    <table border="1">
        <tr>
            <th>Author Id</th>
            <th>Name</th>
            <th>Country</th>
            <th>Gender</th>
        </tr>

        @foreach (var aut in Model)
        {
<tr>
    <td>@aut.aid</td>
    <td>@aut.Name</td>
    <td>@aut.Country</td>
    <td>@aut.Gender</td>
</tr>}

    </table>

</body>

</html>

AuthorBooksBcs6CWebApplication1/Views/Author/AuthorsRecords.cshtml
@model IEnumerable<AuthorBooksBcs6CWebApplication1.Models.Author>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AuthorsRecords</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "authorEntry")
    </p>
    <table border="1" class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.aid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            
            <th>Actions links</th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.aid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            
            <td>
                
                @Html.ActionLink("Edit Author", "Edit", new {  id=item.aid }) |
                @Html.ActionLink("Author Details", "Details", new {  id=item.aid }) |
                @Html.ActionLink("Delete Author", "Delete", new {  id=item.aid })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

AuthorBooksBcs6CWebApplication1/Views/Author/Details.cshtml
@model AuthorBooksBcs6CWebApplication1.Models.Author

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Author</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.aid)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.aid)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Country)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Country)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Married)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Married)
            </dd>
    
        </dl>
    </div>
    <p>
        
        @Html.ActionLink("Back to List", "AuthorsRecords")
    </p>
</body>
</html>

AuthorBooksBcs6CWebApplication1/Views/Author/Edit.cshtml
@model AuthorBooksBcs6CWebApplication1.Models.Author

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Author</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.aid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.aid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.aid, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Married, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Married)
                        @Html.ValidationMessageFor(model => model.Married, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "AuthorsRecords")
    </div>
</body>
</html>

AuthorBooksBcs6CWebApplication1/Views/Author/authorEntry.cshtml
@model AuthorBooksBcs6CWebApplication1.Models.Author
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>authorEntry</title>
</head>
<body>
    <div>
        <h1> Author Enrty Form</h1>
        @using (Html.BeginForm("authorEntry", "Author", FormMethod.Post))
        {
    <table>
        <tr>
            <td>Author Name</td>
            <td>
                @Html.TextBoxFor(model => model.Name)
            </td>
        </tr>
        <tr>
            <td>Country</td>
            <td>
                @Html.DropDownListFor(model => model.Country, (List<SelectListItem>)ViewBag.Countries, "Select")

            </td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                @Html.RadioButtonFor(model => model.Gender, "M")Male
                @Html.RadioButtonFor(model => model.Gender, "F")Female
            </td>
        </tr>

        <tr>

            <td>
                @Html.CheckBoxFor(model => model.Married, true)
            </td>
            <td>Married?</td>
        </tr>

        <tr>
            <td colspan="2">
                <input type="submit" value="Submit" />
            </td>
        </tr>
    </table>}
    </div>
</body>
</html>